In [36]:
import pandas as pd
import numpy as np
from datetime import datetime, timedelta

In [32]:
df = pd.read_csv('../data/clear_data.scv')

In [37]:
df.head(5)

,ride_id,created_at,pickup_lat,pickup_lng,dropoff_lat,dropoff_lng,user_id,driver_id,ride_distance,canceled_by_client,canceled_by_driver,ride_to_suburb
0,000002b3a3014388a6c62fdda1d03de1n,2018-12-14 23:00:00.043000000,49.824671,24.013246,49.784729,24.060303,3900450045004500300042003700310037003800460031...,a429c637c1244bb7a1d606d2b9987bdd,7.97,0,0,0
1,000013de085e4be4a2cd27d9112f7bdbn,2018-10-13 23:59:00.580000000,49.837906,24.029772,49.841217,23.974363,6227785C7862375C7863623F5C7866652E285F2D5C7861...,NaN,5.62,1,0,0
2,000040911549444d8ad461c69370e883n,2018-08-25 21:40:52.537000000,49.839718,23.994425,49.840610,24.029135,62277C6C5C7866386C572C795C7838315C7831645C7863...,7323767ede0349d1a7bfe743a091d63c,3.17,0,0,0
3,0000759fc38a410e8d8802610800ccacn,2018-12-08 13:43:41.357000000,49.829708,24.044172,49.869137,24.010246,62275C7864335C78393135635C6E5C7830355C7839645C...,NaN,5.87,1,0,0
4,0000e61e5282484d943291df7266ee33n,2019-01-18 09:18:44.377000000,49.837013,24.034357,49.832710,23.999216,3300360037004600420041003600300032003500410033...,2913413c2bf748d7932d1d587c8aef13,3.39,0,0,0

In [46]:
week_day, weekend, month, year = [], [], [], []

err = 0
for raw in df.iterrows():
    try:
        created_at = datetime.strptime(raw[1].created_at[:-3], '%Y-%m-%d %H:%M:%S.%f')
        weekday = created_at.weekday()
        week_day.append(int(weekday))
        weekend.append(True if weekday in (5, 6) else False)
        month.append(int(created_at.month))
        year.append(int(created_at.year))
    except:
        err += 1
        week_day.append(None)
        weekend.append(None)
        month.append(None)
        year.append(None)
        
        
    

print(err)
# print(week_day, weekend, month, year)

4409

In [56]:
print(type(week_day[0]))

<class 'int'>

In [53]:
new_df = pd.DataFrame({'week_day': week_day, 'weekend': weekend, 'month': month, 'year': year})

In [54]:
new_df

         week_day weekend  month    year
0             4.0   False   12.0  2018.0
1             5.0    True   10.0  2018.0
2             5.0    True    8.0  2018.0
3             5.0    True   12.0  2018.0
4             4.0   False    1.0  2019.0
5             2.0   False   10.0  2018.0
6             4.0   False    1.0  2019.0
7             6.0    True    9.0  2018.0
8             3.0   False   12.0  2018.0
9             4.0   False    1.0  2019.0
10            1.0   False    2.0  2019.0
11            0.0   False   10.0  2018.0
12            0.0   False   11.0  2018.0
13            1.0   False    1.0  2019.0
14            6.0    True    1.0  2019.0
15            4.0   False   12.0  2018.0
16            6.0    True   12.0  2018.0
17            3.0   False    8.0  2018.0
18            1.0   False    9.0  2018.0
19            3.0   False    2.0  2019.0
20            4.0   False   12.0  2018.0
21            2.0   False   12.0  2018.0
22            4.0   False   11.0  2018.0
23            0.0   False   12.0  2018.0
24            0.0   False   11.0  2018.0
25            6.0    True    9.0  2018.0
26            4.0   False   10.0  2018.0
27            5.0    True   10.0  2018.0
28            0.0   False    9.0  2018.0
29            1.0   False    1.0  2019.0
...           ...     ...    ...     ...
1117270       2.0   False   12.0  2018.0
1117271       3.0   False   11.0  2018.0
1117272       0.0   False    9.0  2018.0
1117273       1.0   False   10.0  2018.0
1117274       2.0   False   10.0  2018.0
1117275       3.0   False   12.0  2018.0
1117276       4.0   False    9.0  2018.0
1117277       5.0    True    8.0  2018.0
1117278       4.0   False    9.0  2018.0
1117279       1.0   False    8.0  2018.0
1117280       1.0   False    1.0  2019.0
1117281       5.0    True    1.0  2019.0
1117282       4.0   False    2.0  2019.0
1117283       0.0   False   12.0  2018.0
1117284       1.0   False    1.0  2019.0
1117285       6.0    True    1.0  2019.0
1117286       2.0   False    1.0  2019.0
1117287       1.0   False   12.0  2018.0
1117288       2.0   False   11.0  2018.0
1117289       5.0    True    9.0  2018.0
1117290       5.0    True   11.0  2018.0
1117291       4.0   False    8.0  2018.0
1117292       6.0    True    9.0  2018.0
1117293       2.0   False   12.0  2018.0
1117294       6.0    True   12.0  2018.0
1117295       6.0    True    1.0  2019.0
1117296       5.0    True   12.0  2018.0
1117297       5.0    True    2.0  2019.0
1117298       4.0   False   11.0  2018.0
1117299       6.0    True   10.0  2018.0

[1117300 rows x 4 columns]

In [55]:
new_df.to_csv("../data/time_data.scv", index=False)